# Generated by Django 6.0.3 on 2026-04-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('province', models.CharField(max_length=50)),
                ('crop_type', models.CharField(max_length=50)),
                ('average_yield_kg_per_hectare', models.FloatField()),
                ('total_farm_value_dollars', models.FloatField()),
                ('avg_rainfall_mm', models.FloatField()),
                ('avg_temperature_c', models.FloatField()),
                ('irrigation_used', models.BooleanField()),
            ],
        ),
    ]
